sudo: false
language: python

python:
  - 3.5
  - 3.6

env:
  - DJANGO=2.0
  - DJANGO=2.1

matrix:
  fast_finish: true
  include:
  - python: "3.6"
    env: TOXENV=flake8
  - python: "3.6"
    env: TOXENV=docs

before_install: pip install codecov
install: pip install tox

script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $DJANGO == '2.0' ]]; then export TOXENV=py35-django20; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $DJANGO == '2.1' ]]; then export TOXENV=py35-django21; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' && $DJANGO == '2.0' ]]; then export TOXENV=py36-django20; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' && $DJANGO == '2.1' ]]; then export TOXENV=py36-django21; fi"
  - tox -e $TOXENV

after_success: codecov
